version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  campick:
    build: ./
    env_file:
      - .env
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    platform: linux/amd64
    ports:
      - "443:443"
    depends_on:
      - mysql
      - redis
    volumes:
      - /etc/letsencrypt/live/campick.shop:/etc/letsencrypt/live/campick.shop:ro

volumes:
  mysql-data:
  redis-data:
